.github/workflows/codespell.yaml
.github/workflows/commitlint.yaml
.github/workflows/conf/yamllint.yaml
.github/workflows/dependencies.yaml
.github/workflows/docker-build.yaml
.github/workflows/golangci-lint.yaml
.github/workflows/yamllint.yaml

This commit adds basic github actions.

ci: add github actions

---

OWNERS

Adds more reviewers to the OWNERS file.

project: add reviewers

---

controllers/lvmcluster_controller.go

Use the finalizer functions provided by the controllerutils pkg.

controllers: use controllerutils finalizer functions

---

.github/workflows/on-pr-submit.yaml

ci: github action to run 'make test' on every pr

---

must-gather/Dockerfile
must-gather/OWNERS
must-gather/README.md
must-gather/collection-scripts/gather
must-gather/collection-scripts/gather_clusterscoped_resources
must-gather/collection-scripts/gather_namespaced_resources

The lvm must-gather will capture lvm related information
from an OCP cluster.

must-gather: initial commit

---

bundle.Dockerfile
bundle/manifests/lvm-operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/lvm-operator-manager-config_v1_configmap.yaml
bundle/manifests/lvm-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/lvm-operator.clusterserviceversion.yaml
bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml
config/manifests/bases/lvm-operator.clusterserviceversion.yaml

This commit checks in the files generated by `make bundle`.
The installMode has also been updated to set OwnNamespace to true.

bundle: generate initial bundle files

---

config/rbac/topolvm_node_role_bindings.yaml

This fixes an error in a previous commit.

yaml: fixes error flagged by yamllint

---

config/rbac/role.yaml
controllers/defaults.go
controllers/lvmcluster_controller.go
controllers/lvmcluster_controller_test.go
controllers/topolvm_storageclass.go

- Implementation of resourceManager interface for topolvm storage class
- Addition of RBAC for operator to manage topolvm storage classes
- Envtest to verify creation and deletion of storage class based on CR

feat: topolvm storage class resource unit implementation

---

bundle/manifests/controller-manager-metrics-service_v1_service.yaml
bundle/manifests/lvm-operator-manager-config_v1_configmap.yaml
bundle/manifests/lvm-operator.clusterserviceversion.yaml
bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
bundle/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/topolvm-controller_v1_serviceaccount.yaml
bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_role.yaml
bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_rolebinding.yaml
bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_role.yaml
bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_rolebinding.yaml
bundle/manifests/topolvm-leader-election_rbac.authorization.k8s.io_v1_role.yaml
bundle/manifests/topolvm-leader-election_rbac.authorization.k8s.io_v1_rolebinding.yaml
bundle/manifests/topolvm-node-scc_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/topolvm-node-scc_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/topolvm-node_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/topolvm-node_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/topolvm-node_v1_serviceaccount.yaml
bundle/manifests/topolvm.cybozu.com_logicalvolumes.yaml
bundle/manifests/vg-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/vg-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
bundle/manifests/vg-manager_v1_serviceaccount.yaml

This commit updates the lvm operator bundle manifests.

bundle: updates bundle manifests.

---

Makefile
olm-deploy/kustomization.yaml
olm-deploy/lvm-catalogsource-image.yaml
olm-deploy/lvm-catalogsource.yaml
olm-deploy/lvm-operator-subscription.yaml
olm-deploy/openshift-storage-namespace.yaml
olm-deploy/openshift-storage-operatorgroup.yaml

Make options and kustomize files to deploy the lvm operator with OLM.

Utils to deploy lvm-operator with Olm

---

bundle/manifests/lvm-operator.clusterserviceversion.yaml

This commit updates the bundle manifests with the recent
manager deployment changes for the vg manager.

bundle: updates bundle manifests

---

Makefile

Fixes the operator-sdk make target

fixes: makefile fixes for operator-sdk

---

config/default/kustomization.yaml

fix: restore namespace to lvm-operator-system

---

doc/user-guide/usage.md

docs: add usage guide for lvmo [skip ci]

---

doc/user-guide/usage.md

Updates the LVMCluster CR example given in the docs
with the recent changes to the CRD.

fix: update LVMCluster example in docs

---

doc/usage/install.md
doc/user-guide/usage.md

Updated the docs with the new default StorageClass name.

fix: updates sc name in docs

---

OWNERS

Updates the OWNERS file with additional reviewers and approvers.

fix: adds more approvers and reviewers

---

OWNERS

Removing jmolmo from the OWNERS file as he is no longer
working on this project.

fix: remove jmolmo from the OWNERS file

---

Makefile
e2e/common.go
e2e/config.go
e2e/lvm/lvm_suite_test.go
e2e/setup_teardown.go
go.mod
go.sum
pkg/deploymanager/LVMCluster.go
pkg/deploymanager/common.go
pkg/deploymanager/config.go
pkg/deploymanager/subscription.go

This test installs and deploy the LVM operator, if not already installed and starts the LVM cluster.

End to end test: Added test suite functions

---

doc/design/thin_pool.md

design: thin pool

---

config/rbac/role.yaml

Updates the rbac manifests with the changes made for
the vg cleanup.

fix: update rbac manifests

---

controllers/defaults.go
controllers/topolvm_controller.go

adding Container Resource Request and limit for the csiResizer container.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
/assign @nbalacha

feat: add resource limit and request for csiResizer

---

bundle/manifests/lvm-operator.clusterserviceversion.yaml

Add perferred namespace and hide crds for logicalVolume, VolumeGroup and
VolumeGroupNodeStatus from the UI.

fix: update csv file

---

api/v1alpha1/lvmcluster_types.go
config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml

build: correct kubebuilder default tag

---

bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml

related PR: https://github.com/red-hat-storage/lvm-operator/pull/172

build: update crd's in the bundle

---

bundle/manifests/topolvm.cybozu.com_logicalvolumes.yaml
config/crd/bases/topolvm.cybozu.com_logicalvolumes.yaml

Update logicalVolume CRD to include the access-type, source ID and type.

fix: update logicalVolume CRD

---

config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_service.yaml

refactor: change controller labels

---

pkg/deploymanager/config.go

fix: added volume snapshot api to e2e client scheme

---

.github/workflows/weekly-build.yaml

Fixed the command to push the docker image.

fix: fixes weekly-build github action

---

bundle/manifests/lvm-operator.clusterserviceversion.yaml
config/manifests/bases/clusterserviceversion.yaml.in
config/samples/lvm_v1alpha1_lvmcluster.yaml

Bug 2090314: Update CSV annotation

---

doc/design/operator.md

In this PR, fixed a small typing error in doc

fix: typo in doc

---

Makefile
bundle.Dockerfile
bundle/manifests/lvm-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml

fix: updated operator-sdk version

---

e2e/ephemeral_check.go
e2e/pvc_check.go
e2e/validation.go

Added additonal debug logs and error checks to the e2e tests.

test: additional logs and error checks in e2e

---

api/v1alpha1/lvmcluster_types.go
bundle/manifests/lvm-operator.clusterserviceversion.yaml
bundle/manifests/lvm.topolvm.io_lvmclusters.yaml
config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
config/rbac/role.yaml
controllers/lvmcluster_controller.go
controllers/lvmcluster_controller_test.go
controllers/suite_test.go

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2124945

fix: update lvmcluster ready status appropriately and add state to its status

---

.github/workflows/golangci-lint.yaml
cmd/metricsexporter/exporter.go
pkg/vgmanager/device_age_test.go

Update the golangci-lint github workflow to use
the latest version.

chore: update golangci-lint version

---

doc/design/operator.md
doc/design/thin_pool.md
doc/dev-guide/lvmo-units.md
doc/dev-guide/reconciler.md
doc/dev-guide/topolvm-csi.md
doc/dev-guide/vg-manager.md
doc/user-guide/usage.md

The LVMO docs were out of date. These have been updated with information on the latest changes.

chore: update the docs

---

bundle/manifests/lvm-operator.clusterserviceversion.yaml
config/manifests/bases/clusterserviceversion.yaml.in

fix: add dissconected env annotation to the CSV

---

bundle/manifests/lvm-operator.clusterserviceversion.yaml
config/manifests/bases/clusterserviceversion.yaml.in

Manual backport of https://github.com/red-hat-storage/lvm-operator/pull/285

Bug 2139776:[release-4.12] fix: add dissconected env annotation to the CSV

---

bundle/manifests/lvm-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml

fix: remove debug logging from the manager auth proxy patch

---

OWNERS

As a part of ownership transitioning efforts, this PR adds @brandisher, @jerpeter1, and @suleymanakbas91 to the OWNERS.

OCPVE-187: Add Chad, Jeremy, and Suleyman to the OWNERS

---

bundle/manifests/lvms-operator.clusterserviceversion.yaml

PR#300 introduced an issue where the CSV is generated with the wrong image. Fixed.

fix: corrects the image in the CSV

---

Makefile

This PR adjusts the `sed` calls in the Makefile to work on both Linux and MacOS.

OCPVE-311: Improve Make targets to work on MacOS as well

---

OWNERS

This PR updates the OWNERS file before integrating Tide for auto-merging.

OCPVE-335: update the OWNERS file

---

OWNERS

Users need to be listed in reviewers to get assigned to reviews

chore: adding everyone back to reviewers so we get assigned

---

docs/design/proposals/logical-volume-manager-storage-api-v2.md

Request to merge the rejected v2 API Proposal

OCPVE-662: docs: v2 api proposal

---

internal/controllers/vgmanager/controller.go
internal/controllers/vgmanager/controller_test.go
internal/controllers/vgmanager/devices.go

Various additional failure tests for cases that can happen during regular reconciliation in vgmanager

OCPVE-747: test: various reconcile failure branch tests

---

cmd/operator/operator.go
internal/cluster/leaderelection.go
internal/cluster/leaderelection_test.go
internal/cluster/namespace_test.go
internal/cluster/sno.go
internal/cluster/sno_test.go
internal/cluster/type_test.go

Adds various test cases so our interactions with the cluster for the setup of the operator are fully tested

OCPVE-747: test: increase cluster functions coverage to 100%

---

bundle/manifests/lvms-operator.clusterserviceversion.yaml
config/manifests/bases/clusterserviceversion.yaml.in
config/manifests/bases/lvms-operator.clusterserviceversion.yaml

Still needs correct adjustment of ticket

OCPBUGS-22383: fix: added 4.13 subscription annotations

---

bundle/manifests/lvms-operator.clusterserviceversion.yaml
config/manifests/bases/clusterserviceversion.yaml.in

Still needs correct Jira Adjustment

OCPBUGS-22384: fix: added 4.12 subscription annotations

---

Dockerfile
Makefile
config/default/manager_custom_env.yaml
config/default/manager_custom_env.yaml.in
go.mod
go.sum
internal/controllers/vgmanager/devices.go
internal/controllers/vgmanager/lsblk/lsblk.go
vendor/github.com/topolvm/topolvm/README.md
vendor/github.com/topolvm/topolvm/lvmd/command/lvm.go
vendor/github.com/topolvm/topolvm/lvmd/command/lvm_json.go
vendor/github.com/topolvm/topolvm/lvmd/lvservice.go
vendor/github.com/topolvm/topolvm/lvmd/vgservice.go
vendor/github.com/topolvm/topolvm/pkg/lvmd/cmd/config.go
vendor/github.com/topolvm/topolvm/pkg/lvmd/cmd/health.go
vendor/github.com/topolvm/topolvm/pkg/lvmd/cmd/root.go
vendor/modules.txt

Used pprof heap analysis to optimize our most pressing heap issues, got rid of around 10mi of floating memory due to badly optimized logging and file reading

chore: optimize vgmanager heap memory

---

bundle/manifests/lvms-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controllers/lvmcluster/controller.go
internal/controllers/lvmcluster/resource/scc.go
internal/controllers/lvmcluster/resource/topolvm_csi_driver.go
internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go
internal/controllers/lvmcluster/resource/topolvm_storageclass.go

fixes various missing update/patches that are required to patch cluster scoped resources in the future

OCPBUGS-27226: fix: add missing permissions to cluster scoped resources

---

.pre-commit-config.yaml
internal/controllers/lvmcluster/controller.go
internal/controllers/lvmcluster/resource/lvm_volumegroup.go
internal/controllers/lvmcluster/resource/scc.go
internal/controllers/lvmcluster/resource/topolvm_csi_driver.go
internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go
internal/controllers/lvmcluster/resource/topolvm_storageclass.go
internal/controllers/lvmcluster/resource/vgmanager.go
internal/controllers/node/removal/controller.go
internal/controllers/vgmanager/controller.go
internal/csi/registrar.go

Reduces general log verbosity of our success cases so that we dont have a spammed log to analyze with failures

NO-JIRA: chore: decrease general log verbosity

---

bundle/manifests/lvms-operator.clusterserviceversion.yaml
config/rbac/role.yaml
config/rbac/topolvm_controller_role.yaml
controllers/scc.go
controllers/topolvm_csi_driver.go
controllers/topolvm_snapshotclass.go
controllers/topolvm_storageclass.go

(cherry picked from commit ac3ea44d0d6175254f3cc0ba99a4997198c2a281)

[release-4.14] OCPBUGS-27403: fix: add missing permissions to cluster scoped resources

---

bundle/manifests/lvms-operator.clusterserviceversion.yaml
config/rbac/role.yaml
config/rbac/topolvm_controller_role.yaml
controllers/scc.go
controllers/topolvm_csi_driver.go
controllers/topolvm_snapshotclass.go
controllers/topolvm_storageclass.go

(cherry picked from commit ac3ea44d0d6175254f3cc0ba99a4997198c2a281)

[release-4.13] OCPBUGS-27404: fix: add missing permissions to cluster scoped resources

---

README.md

Creates a starter section to relay to the official product docs to not get people confused.

NO-JIRA: docs: relay to product docs

---

must-gather/collection-scripts/gather_node_info

Add lsblk command output to must-gather scripts

OCPEDGE-1160: add lsblk output

---

internal/controllers/vgmanager/controller_test.go

Add test case for overprovision ratio changes
to be reflected in lvmd config file

OCPEDGE-1245: feat(tests) add lvmd.yaml test

---

api/v1alpha1/lvmcluster_webhook.go

Fix type on verifyMetadataSize check

OCPBUGS-43523: feat(webhook): fix typo

---

Dockerfile
internal/controllers/lvmcluster/resource/vgmanager_daemonset.go

Create /run/lock directory during dockerfile build required by crun container runtime

OCPBUGS-44660: feat(Dockerfile): create /run/lock

---

go.mod
go.sum
vendor/github.com/topolvm/topolvm/.golangci.yml
vendor/github.com/topolvm/topolvm/Makefile
vendor/github.com/topolvm/topolvm/README.md
vendor/github.com/topolvm/topolvm/cmd/lvmd/app/health.go
vendor/github.com/topolvm/topolvm/cmd/lvmd/app/root.go
vendor/github.com/topolvm/topolvm/internal/controller/node_controller.go
vendor/github.com/topolvm/topolvm/internal/driver/controller.go
vendor/github.com/topolvm/topolvm/internal/driver/internal/k8s/logicalvolume_service.go
vendor/github.com/topolvm/topolvm/internal/driver/node.go
vendor/github.com/topolvm/topolvm/internal/filesystem/util.go
vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm.go
vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm_command.go
vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm_error.go
vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm_lvs.go
vendor/github.com/topolvm/topolvm/internal/lvmd/command/lvm_vgs.go
vendor/github.com/topolvm/topolvm/internal/lvmd/lvservice.go
vendor/github.com/topolvm/topolvm/internal/lvmd/util.go
vendor/github.com/topolvm/topolvm/internal/lvmd/vgservice.go
vendor/github.com/topolvm/topolvm/internal/runners/grpc.go
vendor/github.com/topolvm/topolvm/internal/runners/metrics_exporter.go
vendor/github.com/topolvm/topolvm/pkg/controller/logicalvolume_controller.go
vendor/github.com/topolvm/topolvm/pkg/lvmd/embed.go
vendor/github.com/topolvm/topolvm/versions.mk
vendor/modules.txt

Bump openshift/topolvm version with latest bugfixes.

OCPBUGS-49879: feat(topolvm): update openshift/topolvm

---

go.mod
go.sum
vendor/github.com/topolvm/topolvm/internal/lvmd/lvservice.go
vendor/github.com/topolvm/topolvm/internal/lvmd/util.go
vendor/github.com/topolvm/topolvm/internal/lvmd/vgservice.go
vendor/modules.txt

Bump openshift/topolvm version with latest bugfixes.

OCPBUGS-49931: feat(topolvm): update openshift/topolvm

---

.tekton/multi-arch-build-pipeline.yaml
.tekton/single-arch-build-pipeline.yaml

Adding in missing tasks that will be required soon as well as updated task image references so we don't need to continuously update after bug fixes

OCPEDGE-1588: feat: enterprise contract warnings updates

---

.tekton/lvm-operator-bundle-pull-request.yaml
.tekton/lvm-operator-pull-request.yaml
.tekton/lvms-must-gather-pull-request.yaml
.tekton/multi-arch-build-pipeline.yaml
.tekton/single-arch-build-pipeline.yaml

- Add the apply-tags task to the bundle pipeline
- Add the build-image-index task the bundle pipeline

fix: bundle tagging

---

internal/controllers/lvmcluster/controller.go

Check stale finalizers left by a node which got deleted to prevent resource blocking during its deletion

OCPBUGS-54507: feat(controller): check for stale node finalizers

---

release/bundle/bundle.konflux.Dockerfile

Fix the digest reference and remove extra `@`

[release-4.16] NO-JIRA: Must-Gather konflux reference fix

---

README.md

Add readme section how to create and use loop devices

OCPEDGE-1937: feat(readme): add loop devices info

---

internal/controllers/vgmanager/controller.go
internal/controllers/vgmanager/controller_test.go
internal/controllers/vgmanager/devices.go
internal/controllers/vgmanager/lvm/lvm.go
internal/controllers/vgmanager/lvm/lvm_test.go
internal/controllers/vgmanager/lvm/mocks/mock_lvm.go

Add -y option to vgcreate command when device is wiped in order to accept removing leftovers suggested by LVM

OCPBUGS-58385: feat(wiping): add y option to vgcreate

---

Makefile
README.md
hack/configure_cluster_for_testing.sh
hack/update_cluster_pull_secret.sh

fix: updated the scripting for setting up a test cluster to accommodate the new auth method and simplify the process

NO-JIRA: fix: updated the scripting for setting up a test cluster 
