README.md, controllers/lvmcluster_controller.go, doc/design/README.md
[See preview](https://github.com/rohantmp/lvm-operator/tree/designDoc/doc/design)
=> Design doc

CONTRIBUTING.md, OWNERS
This commit adds the initial CONTRIBUTING and OWNERS files.
Signed-off-by: nbalacha <nibalach@redhat.com>
=> project: Add CONTRIBUTING and OWNERS files

controllers/lvmcluster_controller.go, doc/design/README.md
=> Fix typos, Rename reconcileUnit -> resourceManager, add context.Context to args

api/v1alpha1/lvmcluster_types.go, config/samples/lvm_v1alpha1_lvmcluster.yaml, doc/design/operator.md
This commit fixes typos in the code and docs.
=> ci: fix issues

controllers/lvmcluster_controller.go
Passing the log to all nested called functions is cumbersome.
Since we only run one Reconcile() worker at a time, we can use a
struct level var.
Signed-off-by: Rohan CJ <rohantmp@gmail.com>
=> move logger to Reconciler struct

Makefile
Updated the IMG variable values in the Makefile.
=> build: updated Makefile

controllers/lvmcluster_controller_test.go
- use envtest for verifying reconciliation of lvm cluster CR
=> test: refactor and addition of CR deletion test

config/rbac/role.yaml, controllers/defaults.go, controllers/lvmcluster_controller.go, controllers/lvmcluster_controller_test.go, controllers/topolvm_csi_driver.go
- implemented create and delete reconcile actions on CSIDriver resource
- added rbac roles to manager to manager csidriver resource
=> feat: implementation of csidriver resource unit

config/crd/bases/topolvm.cybozu.com_logicalvolumes.yaml, config/crd/kustomization.yaml, config/default/kustomization.yaml, config/rbac/kustomization.yaml, config/rbac/role.yaml, config/rbac/topolvm_controller_role.yaml, config/rbac/topolvm_controller_role_bindings.yaml, config/rbac/topolvm_controller_service_account.yaml, controllers/defaults.go, controllers/lvmcluster_controller.go, controllers/lvmcluster_controller_test.go, controllers/topolvm_controller.go
- implemented create and delete reconcile actions for TopolvmController
- added rbac roles to manager for manage TopolvmController resource
- added rbac roles for topolvm-controller to manage CSI Controller functionanity
=> feat: implementation of topolvm controller resource unit

config/manager/manager.yaml, main.go
This introduces the WATCH_NAMESPACE env which is set the the operator's
own namespace. This allows the operator to be configured to watch only its
own namespace.
=> controller: operator now watches own namespace

config/rbac/kustomization.yaml, config/rbac/role.yaml, config/rbac/topolvm_node_role.yaml, config/rbac/topolvm_node_role_bindings.yaml, config/rbac/topolvm_node_service_account.yaml, controllers/defaults.go, controllers/lvmcluster_controller.go, controllers/lvmcluster_controller_test.go, controllers/topolvm_node.go
I need to go through unit tests but I think it is good to have a first version of the node daemonset to discuss changes and improvements.
I have **lot of doubts about to use a configmap for storing the lvmd configuration**. It can work for SNO deployments, but we are going to have problems with more that 1 node clusters, because the configmap cannot be different for each node using a Daemonset. 
The only way I see to do that is to use a init container to read a configmap (one per node) and generate a file to be used when lvmd starts. Thoughts?
Update management: 
I only can see two changes to manage:
1. Change of nodes : Now, we do not have the node selector in the CRD. We will need to address this part when we will introduce tyhe node selector
2. Change of lvmd configuration: a new Sc or …
=> CSI Node daemonset

config/rbac/kustomization.yaml
Removes reference to non-existent rbac file in kustomization.yaml
=> manifests: fixes rbac kustomization.yaml

controllers/topolvm_controller.go
=> fix: implement topolvm controller mutate function

controllers/topolvm_node.go, controllers/utils.go, controllers/vgmanager_daemonset.go
Implement the mutate function content for the createorUpdate topolvmdNode
resource.
Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>
=> feat: add mutate function

controllers/topolvm_controller.go, controllers/topolvm_csi_driver.go
=> fix: use consistent return statements across components

controllers/defaults.go, controllers/topolvm_controller.go, controllers/topolvm_node.go, pkg/vgmanager/vgmanager_controller.go
- In #39 values for socket paths are pulled from topolvm project
- However the directories for CSI and LVMd dock paths is same
- In #39 one of the dir is removed erroneously and that is fixed by this
PR to use our own values not to have any clashes.
=> fix: use default socket paths for CSI and LVMd

api/v1alpha1/lvmcluster_types.go, config/crd/bases/lvm.topolvm.io_lvmclusters.yaml
=> fix: validate deviceClass name to be usable in storageClass

bundle/manifests/lvm-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/lvmcluster_controller.go, controllers/scc.go, controllers/suite_test.go, controllers/topolvm_controller.go, controllers/topolvm_node.go, controllers/vgmanager.go, controllers/vgmanager_daemonset.go, controllers/vgmanager_test.go, main.go
This fix creates all resources in the operator namespace instead of the LVMCluster namespace. This is required if, in future, the operator will be extended to watch all namespaces.
=> fix: create all resources in the operator namespace

main.go
Fixed the issue where an incorrect number of arguments caused
the logger to panic.
=> fix: fixes logger panic

Makefile
Adds a make target to set the values of the env vars in manager.env.
=> make: adds target to set mgr env vars

Makefile
Adds a make target to download the operator-sdk binary.
This is required for downstream builds.
=> fix: adds operator-sdk make target

Makefile
This fix adds the package argument to make bundle.
This is required to rename the downstream bundle CSV.
=> feat: allows bundle package name specification

go.mod, pkg/internal/test/mock_exec.go, pkg/vgmanager/lvm.go, pkg/vgmanager/lvm_test.go
- Refactor volume group utility.
- Add helper methods to list Physical Volumes
- Add helper methods to delete VGs and PVs
- Add unit tests for volume group utility
=> Update Volume Group utility

controllers/topolvm_controller.go
Current cert expiry is 356 days. This PR updates the expiry to 3560
days.
=> refactor: Update cert expiry to 10 years

Dockerfile.combined, cmd/metricsexporter/exporter.go, config/default/kustomization.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/kustomization.yaml, config/rbac/lvm_metric_service_config.yaml, config/rbac/lvm_node_role_n_rolebindings.yaml, config/rbac/topolvm_metric_service_config.yaml, config/rbac/topolvm_node_role_n_rolebindings.yaml, go.mod
Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>
=> Adding monitoring capability to lvm-operator

olm-deploy/openshift-storage-namespace.yaml
- Presence of this label on a namespace indicates monitoring machinery to
scrape metrics using servicemonitors
=> fix: add label for namespace for metrics collection

Makefile
This sets the bundle manifests namespace to openshift-storage by
default.
=> fix: sets bundle namespace to openshift-storage

main.go
Sets the zap Development option to false.
=> fix: remove the development log flag

must-gather/collection-scripts/gather_namespaced_resources
Adds the lvmvolumegroup and lvmvolumegroupnodestatus types
the must-gather collection scripts.
=> fix: updates must-gather with new types

Makefile, config/manifests/bases/clusterserviceversion.yaml.in, config/manifests/kustomization.yaml
When a different package name is used for the bundle,
operator-sdk generates a new CSV with the default InstallModes.
This fails to install the operator into the openshift-storage namespace
because of the mismatch with the operatorgroup.
=> fix: fixes csv with different bundle pkg name

Makefile, config/default/kustomization.yaml, config/default/manager_custom_env.yaml.in, config/manager/kustomization.yaml, config/manager/manager.yaml
Env vars for the manager deployment were earlier set using a configmap.
That does not work well with the downstream build mirroring pipeline.
This fix sets the env vars directly in the manager deployment spec.
=> fix: sets env vars in the manager deployment

controllers/topolvm_controller.go, controllers/topolvm_node.go
- overriding entrypoint for sidecars result in incorrect binary paths
while different images are used
- removing explicit command set while deploying containers to use
default entrypoints
=> fix: do not override entrypoint for sidecar images

Dockerfile.combined, controllers/defaults.go, controllers/lvmcluster_controller.go, controllers/suite_test.go, controllers/topolvm_controller.go, controllers/topolvm_node.go, controllers/vgmanager.go, controllers/vgmanager_daemonset.go
- move function to get running pod image into common controller utils
- use operator image from running pod for init containers in topolvm
controller and topolvm node
=> fix: use operator image for init containers

Dockerfile.combined, Dockerfile.vgmanager
CentOS Linux 8 repositories were removed from the mirror network on
January 31 [1]. That breaks the combined and vgmanager images, which
should switch to CentOS Stream 8.
[1] - https://lists.centos.org/pipermail/centos-devel/2021-December/098779.html
=> Use CentOS Stream 8 for images

.github/workflows/docker-build.yaml, Dockerfile.combined, Makefile
- Full repo path to centos:stream8 in Dockerfile.combined
- Add test as subtarget to docker-build-combined
- Build docker combined image as part of CI builds
=> ci: build combined dockerfile as part of CI

pkg/vgmanager/vgmanager_controller.go
Fixes a bug where the lvmvolumegroupnodestatus was not updated correctly
for an existing VG. When adding a new device and restarting the
vg-manager pod, the device is added to the LVM VG but is not updated in
the lvmvolumegroupnodestatus or the LVMCluster status.
fixes: #105
=> fix: updates lvmvolumegroupnodestatus for vg

doc/usage/install.md
Updated the install instructions to point to the lvm-operator
image in quay.io/ocs-dev.
=> fix: updates prebuilt img location in doc

controllers/lvmcluster_controller_test.go, controllers/topolvm_storageclass.go
Replaced "topolvm-" with "odf-lvm" in the storageclass name.
=> fix: renamed storageclass to remove topolvm

pkg/internal/block_device.go, pkg/internal/exec.go, pkg/vgmanager/filter.go
- filter out loop devices based on Major number from lsblk
- check whether the back-file is being used by k8s for mounting block
devices and skip using that loop device in volume groups ops
Fixes: #97
=> fix: skip in-use loop devices during vgcreate/vgextend

Makefile, config/prometheus/kustomization.yaml, config/prometheus/prometheus_rules.yaml, monitoring/alerts/alerts.jsonnet, monitoring/alerts/vgalerts.libsonnet, monitoring/config.libsonnet, monitoring/jsonnetfile.json, monitoring/mixin.libsonnet
Adding an alert mixins framework into LVM Operator.
Makefile is modified to generate the prometheus alert yaml file.
Added 'VolumeGroupUsageAtThreshold' alert which will be triggered if
volumegroup usage goes beyond the threshold percentage (default set to 75%)
Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>
=> Adding an alert mechanism into lvm-operator

Makefile
=> makefile: allow podman usage via makefile

Makefile
https://bugzilla.redhat.com/show_bug.cgi?id=2047173
=> build: add nameprefix to the controller manager

.github/workflows/docker-build.yaml, Dockerfile, Dockerfile.combined, Dockerfile.vgmanager, go.mod
=> build: update go 1.16 to 1.17

config/rbac/vg_manager_role.yaml, pkg/vgmanager/vgmanager_controller.go
This commit implements the nodeSelector check in
vgmanager.
=> fix: implements the nodeSelector check

pkg/vgmanager/vgmanager_controller.go
This commit refactors the vgmanager-controller code.
=> fix: refactors vgmanager-controller code

.github/workflows/golangci-lint.yaml
=> ci: bump golangci-lint version to v1.45.2

controllers/lvm_volumegroup.go
The func does not return an error if there is an error and always return
nil. Fix the same via returning and error if there is a failure.
=> fix: fix ensureCreated of lvmVG via returning an error

controllers/scc.go
The func does not return an error if there is an error and always return
nil. Fix the same via returning and error if there non-expected failure.
=> fix: fix ensureDeleted of openshiftSccs via returning an error

Makefile
Added make target to install ginkgo and gomega
=> e2e: added make target to install ginkgo

must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_node_info
Add node related commands to must-gather output
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>
=> fix: add node related commands to must-gather

controllers/lvm_volumegroup.go, controllers/lvmcluster_controller.go, controllers/scc.go
=> refactor: refactor the logs of lvmcluster controller

controllers/lvm_volumegroup.go, controllers/lvmcluster_controller.go, controllers/suite_test.go, main.go, pkg/vgmanager/vgmanager_controller.go
The vgmanager will now remove the vg and the lvmd.conf
file when the LVMCluster is deleted.
=> feat: cleanup lvm resources on delete

must-gather/collection-scripts/gather_clusterscoped_resources, must-gather/collection-scripts/gather_namespaced_resources
Add commands in must-gather to capture snapshot related
kubernetes objects.
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>
=> fix: add snapshot related commands in must-gather

pkg/vgmanager/lvm.go
The --nolocking arg is not meant to be used in non
cluster setups.
=> fix: removes the --nolocking lvm arg

controllers/defaults.go, controllers/topolvm_controller.go, controllers/topolvm_node.go, controllers/vgmanager_daemonset.go
Add labels to the topolvm-controller, topolvm-node, vg-manager
for example:
app.lvm.openshift.io: topolvm-controller
app.lvm.openshift.io: topolvm-node
app.lvm.openshift.io: vg-manager
=> refactor: add simillar labels to the each components

pkg/vgmanager/vgmanager_controller.go
This fix returns a nil error if the LVMVolumeGroup is not
found, allowing the cleanup reconciliation process to complete
after an initial failure.
=> fix: ignore LVMVolumeGroup NotFound error

config/rbac/topolvm_metric_service_config.yaml
Updates the `service` config to use the new label key `app.lvm.openshift.io`. 
=> fix: fix labels for topolvm-node-metrics service

pkg/deploymanager/LVMCluster.go
Updated the sample LVMCluster CR used by e2e tests with the thin pool configuration.
=> fix e2e: added thin pool configuration to lvm cluster used by e2e tests

Makefile, e2e/config.go, e2e/lvm/lvm_suite_test.go, e2e/validation.go, pkg/deploymanager/config.go
This test validates all the resources created by LVMO
=> test: added test to validate the LVMO resources

bundle/manifests/lvm-operator-manager-config_v1_configmap.yaml, config/manager/manager.env, controllers/defaults.go
Topolvm image was updated to 0.11.0 only in go.mod and makefile.
This PR updates the image version in all the required places.
=> fix: update topolvm csi image to 0.11.0

bundle/manifests/lvm-metrics_rbac.authorization.k8s.io_v1_role.yaml, bundle/manifests/lvm-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/lvm-node-metrics_v1_service.yaml, bundle/manifests/lvm-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, bundle/manifests/lvm-operator.clusterserviceversion.yaml, bundle/manifests/lvm.topolvm.io_lvmclusters.yaml, bundle/manifests/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml, bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml, bundle/manifests/prometheus-lvmo-rules_monitoring.coreos.com_v1_prometheusrule.yaml, bundle/manifests/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/topolvm-leader-election_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/topolvm-metrics_rbac.authorization.k8s.io_v1_role.yaml, bundle/manifests/topolvm-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml, bundle/manifests/topolvm-node-metrics_v1_service.yaml, bundle/manifests/vg-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/vg-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
The openshift-CI was failing because the manifests had not
been updated for a long time and were missing key resource definitions.
=> fix: updates bundle manifests

config/prometheus/prometheus_rules.yaml, monitoring/alerts/vgalerts.libsonnet, monitoring/config.libsonnet
Adds alerts for thin pool data and metadata usage.
Provides near full (75%) and critical (85%) usage alerts.
Note: We don't have thin pool name in the alerts since topolvm does not provide it as of now.  But since we support only one thin pool per volume group, current alerts should suffice (IMO). 
We can update it to include thin pool names once topolvm shows thin pool name in the metric labels. 
Tested with lower thresholds.
=> feat: adds alerts for thin pool usage

bundle/manifests/lvm-operator.clusterserviceversion.yaml, bundle/manifests/prometheus-lvmo-rules_monitoring.coreos.com_v1_prometheusrule.yaml
After running `make bundle` locally few files got updated and new files also got added.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
/cc @nbalacha
=> fix: add missing files for `make bundle`

bundle/manifests/lvm-operator.clusterserviceversion.yaml, config/manifests/bases/clusterserviceversion.yaml.in, config/samples/kustomization.yaml
CSV was updated directly under the manifests directory. This PR fixes
it. Makes correct changes and runs `make bundle` to auto generate the
csv file.
Following changes are made the the csv:
1. Add suggested namespace annotation.
2. Add category
3. Mark certain CRDs as internal so that they are not visible in the UI.
=> fix: update csv correctly.

Makefile, bundle/manifests/lvm-operator.clusterserviceversion.yaml, bundle/manifests/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, config/default/manager_custom_env.yaml.in, config/manager/manager.env, config/rbac/topolvm_controller_role.yaml, config/rbac/topolvm_controller_role_bindings.yaml, controllers/defaults.go, controllers/topolvm_controller.go
ref: https://kubernetes-csi.github.io/docs/external-snapshotter.html
=> feat: add a csi-snapshotter as a sidecar into topolvm_controller

bundle/manifests/vg-manager-clusterrole_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/vg-manager-clusterrolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/vg-manager-role_rbac.authorization.k8s.io_v1_role.yaml, bundle/manifests/vg-manager-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml, config/rbac/kustomization.yaml, config/rbac/vg_manager_clusterrole.yaml, config/rbac/vg_manager_clusterrole_binding.yaml, config/rbac/vg_manager_role.yaml
=> build: convert vg manager clusterrole into role as per requirements 

doc/dev-guide/index.md, doc/dev-guide/lvmo-units.md, doc/dev-guide/reconciler.md, doc/dev-guide/topolvm-csi.md, doc/dev-guide/vg-manager.md
=> docs: add dev guide explaining lvmo components [skip ci]

doc/dev-guide/vg-manager.md
=> fix: fixes typo in vg_manager.md

bundle/manifests/controller-manager-metrics-service_v1_service.yaml, bundle/manifests/lvm-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, bundle/manifests/lvm-operator.clusterserviceversion.yaml
=> build: update labels in the bundle

e2e/config.go, e2e/lvm/lvm_suite_test.go, e2e/lvm/pvc_test.go, e2e/testdata.go, e2e/validation.go, pkg/deploymanager/LVMCluster.go
this test creates pvc and pod and verifies the status of pvc to be bound and pod to be running, and cleans them up.
=> test: to check the status of pvc as bound and pod as running

config/manifests/bases/clusterserviceversion.yaml.in, config/samples/kustomization.yaml
CSV was updated directly under the manifests directory. This PR fixes
it. Makes correct changes and runs `make bundle` to auto generate the
csv file.
Following changes are made the the csv:
1. Add suggested namespace annotation.
2. Add category
3. Mark certain CRDs as internal so that they are not visible in the UI.
(cherry picked from commit 2ffe7ccec0f8fed466f51bf37beb65e91d15174b)
=> Bug 2083129: update csv correctly

pkg/deploymanager/common.go, pkg/deploymanager/config.go, pkg/deploymanager/subscription.go
replaced all clients with a controller runtime client.
=> e2e test: unified the clients

.github/workflows/golangci-lint.yaml
Updates the golangci-lint github workflow to specify the version
of go to be used.
=> fix: specify the go version to be used

.github/workflows/weekly-build.yaml
This adds a github action to build and push the operator
image to quay every Monday.
=> chore: github action to build the operator every week

pkg/vgmanager/vgmanager_controller.go
This commit updates the lvcreate command used to create
the thinpool with the -Z option to enable zeroing. This removes
the requirement that the thin_pool_zero option be enabled in the
lvm.conf.
=> fix: creates the thinpool with the -Z option

bundle/manifests/prometheus-lvmo-rules_monitoring.coreos.com_v1_prometheusrule.yaml, config/prometheus/prometheus_rules.yaml, monitoring/alerts/vgalerts.libsonnet
Trigger VolumeGroupUsage alerts only if actual size is occupied via the thin pool.
`VolumeGroupUsageAtThresholdNearFull` will be sent when used VG size and
thin pool size exceeds 75%.
`VolumeGroupUsageAtThresholdCritical` will be sent when VG size and thin
pool size exceeds 85%.
Testing
Current behavior: size-percent is 90
```
sh-4.4# vgs
VG  #PV #LV #SN Attr   VSize  VFree
vg3   1   1   0 wz--n- <1.46t 149.04g
sh-4.4# lvs
LV          VG  Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
thin-pool-3 vg3 twi-a-tz-- <1.31t             0.00   9.94
```
- VG critical alert trigger even though thin pool is not using any real space.
------------------------------------------------------------------------------------------------------------
Behavior after this PR: 
- size …
=> send vg alerts only when thin pool alerts are also triggered

api/v1alpha1/lvmcluster_types.go, bundle/manifests/lvm.topolvm.io_lvmclusters.yaml, bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml, config/crd/bases/lvm.topolvm.io_lvmclusters.yaml, config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml
SizePercent determines vg size used for creating
the thin pool. Currently the default size is 75.
This PR changes the default size to 90
=> Update default size percent to 90

controllers/topolvm_storageclass.go
This commit marks the topolvm storageClass as the default
if there are no other storageClasses that are present or
is no other class is marked default.
=> fix: mark the topolvm storageclass as default

test/performance/operf.go
LVM operator performance tests (sc usage + lvmcluster creation) based on https://github.com/red-hat-storage/lvm-operator/pull/69
Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>
=> test: script for testing operator performance

bundle/manifests/lvm-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/defaults.go, controllers/topolvm_controller.go, controllers/topolvm_node.go, controllers/vgmanager_daemonset.go
[Reference doc](https://docs.google.com/spreadsheets/d/1GGjmVCDezVyay0jzKKAqyGxuDOU6ud68vB__FJ-mHJc/edit#gid=324255029)
------------------------------
Testing:
1. 50 POD/PVC
- No OOMKilled error observed. But looks like lvmd container might have restarted in the topolvm-node pod.
- It took 20 minutes (approximately double the current time) to create 50 pods.
``` Every 2.0s: oc get pods                                                 localhost.localdomain: Fri Jun 17 14:54:14 2022
NAME                                               READY   STATUS    RESTARTS       AGE
lvm-operator-controller-manager-5d69d47698-b5qm8   3/3     Running   0              49m
topolvm-controller-55d8fd4665-cxlbh                5/5     Running   0              48m
topolvm-node-f2vbw …
```
=> fix: update resource request and limits across containers

bundle/manifests/topolvm.cybozu.com_logicalvolumes.yaml, config/crd/bases/topolvm.cybozu.com_logicalvolumes.yaml
Updates the LVMO manifests with the modified LogicalVolumes.topolvm.cybozu.com CRD.
=> Update the LogicalVolumes.topolvm.cybozu.com CRD. 

Makefile
This commit updates the Makefile to use the downloaded
operator-sdk so as to use a fixed version on every system.
It also updates the operator-sdk version.
=> fix: use downloaded operator-sdk

bundle.Dockerfile, bundle/manifests/lvm-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml
This commit regenerates the bundle manifests with
the new operator-sdk version.
=> fix: update bundle with updated operator-sdk

bundle/manifests/lvm-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml
changed service account name from default controller-manager to
lvm-controller-manager to distinguish it with various other operators
installed in same namespace.
Output from terminal:
[riyasinghal@fedora lvm-operator]$ oc get sa -n openshift-storage
NAME SECRETS AGE
builder 2 3m36s
default 2 3m36s
deployer 2 3m36s
lvm-catalogsource 2 3m36s
lvm-controller-manager 2 2m34s
topolvm-controller 2 2m37s
topolvm-node 2 2m35s
vg-manager 2 2m39s
=> fix: renamed service account

e2e/pvc_check.go, e2e/validation.go
This commit corrects the check for Snapshot.Status.ReadyToUse
and also reduces the interval at which the check is performed.
=> fix: panic when checking if snapshot is ready

.github/workflows/codespell.yaml
Codespell recently started tagging valid words as errors.
This commit adds files and words to those to be excluded/ignored
in order to get around the problem.
=> fix: updates codespell options

.github/workflows/conf/yamllint.yaml, e2e/ephemeral_check.go, e2e/lvm_suite_test.go, e2e/testdata/ephemeral_tests/ephemeral-clone.yaml, e2e/testdata/ephemeral_tests/ephemeral-snapshot-restore.yaml, e2e/testdata/ephemeral_tests/ephemeral-volume-snapshot.yaml, e2e/testdata/ephemeral_tests/pod-ephemeral-volume-device.yaml, e2e/testdata/ephemeral_tests/pod-ephemeral-volume-mount.yaml, e2e/testdata/ephemeral_tests/pod-volume-device-template.yaml, e2e/testdata/ephemeral_tests/pod-volume-mount-template.yaml
This PR adds the test for ephemeral volume, by creating a pod for ephemeral volume and confirming its lifetime.
Also creates snapshot and clone for the ephemeral volume.
=> test: added the test for ephemeral volume in e2e

pkg/vgmanager/filter.go, pkg/vgmanager/vgmanager_controller.go
Moved the filterAvailableDevices function to the
vgmanager_controller.go function. The filter.go will
have only the filter map and functions.
=> refactor: move function to different file

Makefile
ref: https://go.dev/doc/go-get-install-deprecation
=> build: use go install instead of depricated go get

pkg/vgmanager/device_age_test.go, pkg/vgmanager/filter_test.go
This commit adds unit tests for filter.go and device_age.go
as part of the initiative to improve code coverage.
=> tests: added unit tests for some vgmanager files

pkg/vgmanager/vgmanager_controller.go
Based on feedback and performance tests, the chunksize for the lvm thinpool is being reduced to 128KiB.
=> fix: set the thinpool chunksize to 128KiB

api/v1alpha1/lvmcluster_types.go, controllers/conditions.go, controllers/lvmcluster_controller.go
The responsibility of CR verification moved to the validation webhook.
=> fix: do not verify lvmcluster from controller anymore

pkg/internal/block_device.go, pkg/vgmanager/vgmanager_controller.go
Earlier we were supporting only `/dev/disk/by-path/` and `dev` kind of paths. With the current approach we will support all kind of paths.
The status will show the names only now onwards.
=> fix: allow all kind of paths

bundle/manifests/lvm-operator.clusterserviceversion.yaml, config/manifests/bases/clusterserviceversion.yaml.in
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2118972
full_version label is added in the DS build pipeline if and only if we have some labels defined in the CSV. currently, LVMO CSV does not hold any labels. The PR does add few labels into the CSV.
=> build: add labels in the csv

Makefile, bundle/manifests/lvm-operator.clusterserviceversion.yaml, config/manager/manager.env, controllers/defaults.go
Updates the CSI sidecar image versions to match those used by TopoLVM.
=> CSI sidecar image version updates

e2e/validation.go, pkg/deploymanager/config.go
A missing volumesnapshot scheme caused the e2e validation tests to fail on the release-4.11 branch. This has been fixed. Additional log messages have been added to the e2e tests for debugging. The topolvm node daemonset status check has been added. Also fixed golang-lint errors.
=> Bug 2129734: test: fix volumesnapshotclass validation e2e tests

pkg/internal/block_device.go, pkg/vgmanager/filter.go, pkg/vgmanager/vgmanager_controller.go
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2124868
=> feat: filter child block devices also

pkg/vgmanager/vgmanager_controller.go
Deleting the lvmvolumegroup CR does not clean the VG entry in the
lvmvolumegroupnodestatus if lvmdconfig file does not exists and returns
immediately. Fix the same via updating the lvmvolumegroupnodestatus.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2124202
=> fix: deletion of lvmcluster which includes wrong paths

Makefile, olm-deploy/openshift-storage-namespace.yaml
This fixes the following:
- Added the podsecurity labels to the openshift-storage namespace yaml.
- Upgraded to opm v1.26.2 to fix a permission issue with accessing the sqlite db in te catalog.
=> fix: fixes deploy-with-olm on ocp 4.12

e2e/helper.go, e2e/lvmcluster.go
The PSA changes in OCP 4.12 prevent pods from starting as ns are labeled restricted by default. This commit sets the label pod-security.kubernetes.io/enforce: "baseline"
on the lvm-endtoendtest to allow the test pods to run. This also renames a file to conform to the naming convention.
=> fix: add test ns labels for PSA

.github/workflows/codespell.yaml, .github/workflows/golangci-lint.yaml, e2e/validation.go
Removed the check for the topolvm node deployment status in the release-4.11. 
As no disks are added, the topolvm-node pods never become ready.
=> Bug 2133742: fix: fixes e2e tests for release-4.11

config/manager/manager.yaml
The namespace created by make deploy was missing the PSA labels, preventing the topolvm-node and vg-manager pods from starting on OCP 4.12. This commit adds them and the missing cluster monitoring label.
=> fix: add missing ns labels for make deploy

.github/workflows/manual-build.yaml
This sets the value of the IMG env variable in the github wokflow.
=> fix: github action for lvmo manual build

.github/workflows/manual-build.yaml, .github/workflows/weekly-build.yaml
Updates the weekly build github action to call a second workflow. This will allow us to trigger a build for red-hat-storage/topolvm as part of the weekly build.
=> chore: update the weekly build github action

doc/user-guide/upgrade.md
Specify that upgrades from release 4.11 to a higher version are not supported due to a breaking change in TopoLVM.
=> doc: add an upgrade doc

config/default/manager_auth_proxy_patch.yaml, config/default/manager_config_patch.yaml, config/default/manager_custom_env.yaml.in, config/default/manager_webhook_patch.yaml, config/manager/manager.yaml, controllers/constants.go, controllers/topolvm_controller.go, controllers/topolvm_node.go, controllers/vgmanager_daemonset.go, e2e/helper.go, e2e/subscription.go, olm-deploy/openshift-storage-namespace.yaml
This PR enables management workload partitioning, which was introduced in [this proposal.](https://github.com/openshift/enhancements/blob/master/enhancements/workload-partitioning/management-workload-partitioning.md)
Signed-off-by: Suleyman Akbas <sakbas@redhat.com>
=> OCPVE-235: Add management workload annotations

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/constants.go, controllers/topolvm_controller.go, controllers/topolvm_node.go, controllers/vgmanager_daemonset.go
This PR reduces CPU and Memory requests or all the pods to the "at rest" values shown in [the analysis document](https://docs.google.com/spreadsheets/d/1eLBkG4HhlKlxRlB9H8kjuXs5F3zzVOPfkOOhFIOrfzU/edit#gid=0). It also removes all the CPU and Memory limits from the containers.
Signed-off-by: Suleyman Akbas <sakbas@redhat.com>
=> OCPVE-234: Reduce CPU and Memory requests and remove limits

Dockerfile, Dockerfile.combined, Dockerfile.vgmanager
This PR reduces the size of the images by
- specifying `--ldflags "-s -w"` in go build commands, which will strip debug information and remove DWARF symbols, reducing the size of the binary.
- changing the base image from `quay.io/centos/centos:stream8` to `registry.access.redhat.com/ubi8/ubi-minimal:8.7` on vgmanager and combined Dockerfiles.
The result is as follows:
Before: 
After:
The difference is big for vgmanager and combined images because of the base image change.
Signed-off-by: Suleyman Akbas <sakbas@redhat.com>
=> OCPVE-236: Reduce image size

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, controllers/constants.go, controllers/topolvm_controller.go, controllers/topolvm_node.go
This PR adds resource requests for the `file-checker`, `self-signed-cert-generator` initcontainers, and `kube-rbac-proxy` container. 
Not specifying resource requests for initcontainers might cause problems with ResourceQuotas like in https://github.com/kubedb/project/issues/311.
Follow-up for #303
=> OCPVE-234: Add further resource requests

api/v1alpha1/lvmcluster_types.go, api/v1alpha1/lvmcluster_webhook.go, api/v1alpha1/lvmvolumegroup_types.go, bundle/manifests/lvm.topolvm.io_lvmclusters.yaml, bundle/manifests/lvm.topolvm.io_lvmvolumegroups.yaml, bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/crd/bases/lvm.topolvm.io_lvmclusters.yaml, config/crd/bases/lvm.topolvm.io_lvmvolumegroups.yaml, config/samples/lvm_v1alpha1_lvmcluster.yaml, controllers/lvm_volumegroup.go, controllers/lvmcluster_controller_test.go, doc/user-guide/usage.md, e2e/lvmcluster.go, pkg/vgmanager/vgmanager_controller.go
This PR enables the support of multiple storage/device classes. 
- `api/v1alpha1/lvmcluster_types.go`: Introduces a new field `Default` in `DeviceClass`, which indicates whether the device-class is the default.
- `api/v1alpha1/lvmcluster_webhook.go`: Removes the validation for a single device class. Adds another validation to make sure there is only one default device class. If there is only one device class, it is considered the default one internally even if `Default` field is not set, to make the upgrades easier. Specifying more than one default device class errors TopoLVM.
- `api/v1alpha1/lvmvolumegroup_types.go`: Introduces a new field `Default` in `LVMVolumeGroupSpec` which matches the field in `DeviceClass` and is used internally. `controllers/lvm_volumegroup.go` change handles the …
=> OCPVE-253: Support multiple storage/device classes

api/v1alpha1/lvmcluster_webhook.go
This PR adds a validation to enforce users to specify path lists for devices when they use multiple device classes. This makes the device distribution over device classes transparent and does not give the responsibility to the operator to do this automagically.
=> OCPBUGS-8102: Make path list mandatory for multiple device classes

api/v1alpha1/lvmcluster_webhook.go
This PR enhances the error message when multiple device classes are used, but no paths specified for at least one of them. The new error message includes all the device class names that do not have paths.
=> OCPBUGS-8102: Include all the device class names in the error message

Makefile, bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/manager/manager.env, controllers/defaults.go
This PR updates CSI sidecar image versions to match [the ones](https://github.com/openshift/topolvm/blob/main/csi-sidecars.mk) on the rebased TopoLVM repo. 
Signed-off-by: Suleyman Akbas <sakbas@redhat.com>
=> OCPVE-287: Update CSI sidecar image versions

Makefile, bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/manifests/bases/kustomization.yaml, config/manifests/kustomization.yaml
This PR provides a way to add REPLACES and SKIP_RANGE in the CSV, which is required by OLM while upgrading a CSV to the newer version.
=> OCPBUGS-11309: Provide a way to add replaces and skips in the CSV

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/clusterserviceversion.yaml.in, config/manifests/bases/lvms-operator.clusterserviceversion.yaml
This PR adds the missing workload management annotation to the CSV.
=> OCPBUGS-11426: Add missing workload management annotations

controllers/lvmcluster_controller_watches.go, controllers/topolvm_storageclass.go
This PR adds a watcher for storage class objects to the LVM operator. So, when lvms storage classes are modified, they will immediately be reconciled. Also, when setting an lvms storage class as default, we now check if the associated device class is the default one instead of randomly assigning a storage class as default.
=> OCPBUGS-11047: Add a watcher for storage class objects to the operator

controllers/topolvm_controller.go, controllers/topolvm_node.go
This PR provides a fix for non-changing initcontainer images during an upgrade. 
`controllers/topolvm_controller.go`: Adds initcontainers to reconciliation of TopoLVM Controller so that they are properly reconciled. 
`controllers/topolvm_node.go`: Adds initcontainers to reconciliation of TopoLVM Node so that they are properly reconciled.
=> OCPBUGS-11893: Enable updating initcontainer images during an upgrade

pkg/vgmanager/vgmanager_controller.go
This PR reduces reconcile interval for delayed devices from one minute to thirty seconds. This improves the waiting time for the users by reducing the time for `vg-manager` to create the lvmd config file and let `topolvm-node` start working.  
Before:
After:
`topolvm-node` starting time is almost halved.
=> OCPVE-310: Reduce reconcile interval for delayed devices

Makefile, config/default/manager_custom_env.yaml, config/manager/kustomization.yaml, hack/verify-bundle.sh, hack/verify-deps.sh, hack/verify-generated.sh, hack/verify-gofmt.sh
This PR adds some verifications to run on OpenShift CI. This will make it easier for multiple people to work on the same codebase. 
`config/default/manager_custom_env.yaml` and `config/manager/kustomization.yaml` are both generated, so this PR adds them as well to make a clean start.
=> OCPVE-334: Add verify target to check go formatting and generated files

Makefile
This PR changes the VERSION environment variable to OPERATOR_VERSION in the Makefile to prevent conflicts with other environment variables.
=> OCPVE-334: Change VERSION to OPERATOR_VERSION in the Makefile

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/manifests/bases/clusterserviceversion.yaml.in, config/manifests/bases/lvms-operator.clusterserviceversion.yaml
This should list the operator in Openshift for ARM as brought up in https://github.com/openshift/lvm-operator/issues/335
=> OCPBUGS-13364: fix: Added a tag for arm64 to have it pulled into Openshift for ARM

api/v1alpha1/lvmvolumegroupnodestatus_types.go, cmd/vgmanager/main.go, controllers/lvmcluster_controller.go, pkg/vgmanager/devices.go, pkg/vgmanager/devices_test.go, pkg/vgmanager/status.go, pkg/vgmanager/vgmanager_controller.go
This PR refactors status reporting logic to send updates more often.
- `api/v1alpha1/lvmvolumegroupnodestatus_types.go`: Adds a new `Progressing` status to volume groups.
- `cmd/vgmanager/main.go`: Minor fixes and cleanup.
- `controllers/lvmcluster_controller.go`: Modifies LVMCluster to report `Ready` only when all the volume groups are ready.
- `pkg/vgmanager/devices.go`: Moves finding available devices logic into a separate file.
- `pkg/vgmanager/devices_test.go`: Adds a unit test.
- `pkg/vgmanager/status.go`: Implements functions for volume group status calculation and setting.
- `pkg/vgmanager/vgmanager_controller.go`: Adds status updates for each failure and success.
=> OCPBUGS-10534: Refactor status reporting logic to send updates more often

controllers/lvm_volumegroup.go, controllers/topolvm_controller.go, controllers/topolvm_csi_driver.go, go.mod
Check create or update functions and refactor code a little bit =)
PART 1
=> OCPVE-333: check create or update functions

README.md, docs/README.md, docs/design/lvm-operator-manager.md, docs/troubleshooting.md
This PR adds a troubleshooting guide for some common problems users encounter.
=> OCPVE-233: Add a troubleshooting guide

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/constants.go, controllers/lvmcluster_controller.go, controllers/persistent-volume-claim/controller.go, controllers/persistent-volume/controller.go, controllers/utils.go, docs/design/lvm-operator-manager.md, main.go, pkg/internal/block_device.go, pkg/vgmanager/vgmanager_controller.go
This PR adds a PV and a PVC controller to the LVM Operator. 
- The PV controller watches for PVs created by LVMS and publishes an event if their `spec.claimRef` gets deleted: 
- The PVC controller watches for the PVCs created by LVMS and publishes an event if the PVC requests a storage greater than available capacity on any node:
=> OCPVE-349: Add PV and PVC controllers to publish events

Makefile, controllers/lvm_volumegroup.go, controllers/topolvm_controller.go, controllers/topolvm_csi_driver.go, controllers/topolvm_node.go, test/e2e/setup_teardown.go
Add owner reference to created objects. CR owns all created objects for given cluster
=> OCPVE-330: Add add owner reference to created objects

controllers/persistent-volume-claim/controller.go, controllers/persistent-volume-claim/controller_test.go, controllers/persistent-volume/controller.go, go.mod, main.go
Otherwise if a PVC is created without storageClassName, LVM Operator will crash and cause a panic.
Also removes unnecessary API Reader in PVC controller and cleans up logging, introduces test cases for ignore cases
=> OCPBUGS-15576: fix: ensure panic safety in PVC controller for non set storageClassName

api/v1alpha1/webhook_suite_test.go, controllers/suite_test.go
This enables the test suites that were disabled in https://github.com/openshift/lvm-operator/commit/3ce11a8bfccbde2032e489abc82b4e35348e7251 back in may by accident. Potentially the ginkgo logs could cause issues in pipeline parsers if the stdout is parsed, not sure if that changed since then. Other than that it should run fine
=> OCPVE-606: fix: reenable falsly disabled integration tests

main.go, pkg/cluster/leaderelection.go, pkg/cluster/leaderelection_test.go
Uses https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-control-plane to discover master nodes instead of simply checking if there is one node.
also adds tests for various node configurations in the Wild and moves the resolve logic out of main.go
=> OCPBUGS-11486: fix: correctly determine master nodes by label for SNO

controllers/lvmcluster_controller.go, controllers/topolvm_controller.go, main.go
This passes all leader election settings to the controllers so that all controllers have unified Leader Election Configuration.
=> OCPBUGS-11486: fix: passthrough unified LE settings to all controllers

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/lvmcluster_controller_integration_test.go, controllers/lvmcluster_controller_watches.go, controllers/node/removal_controller.go, controllers/suite_test.go, main.go, pkg/cluster/leaderelection.go, pkg/cluster/leaderelection_test.go, pkg/cluster/sno.go
In case the operator gets deployed in a multi-node environemnt the `LVMVolumeGroupNodeStatus` is orphaned when a node is removed. This is unintended. We need a logic that can succesfully remove this NodeStatus whenever there is a removed Node.
Unfortunately since the status update of LVMCluster is currently assuming the correct presence of the `LVMVolumeGroupNodeStatus`, the only way I found to fix this issue would be to
1. delete the `LVMVolumeGroupNodeStatus` in the status update of `LVMCluster` in case the node does not exist anymore and the Status check finds an orphaned status without a node. potentially expensive since now `LVMCluster` has to compare all nodes and check if the LVMNodeVolumeStatus exists. Also the removal will be delayed from the Node. 
2. delete the …
=> OCPBUGS-13558: fix: ensure LVMVolumeGroupNodeStatus is removed by dedicated cleanup controller in case of multi-node

pkg/vgmanager/lv_attr.go, pkg/vgmanager/lv_attr_test.go, pkg/vgmanager/lvm.go, pkg/vgmanager/vgmanager_controller.go, pkg/vgmanager/vgmanager_controller_test.go, vendor/github.com/go-logr/logr/testr/testr.go, vendor/modules.txt
This introduces new checks when the LV was already created as a thin pool to ensure correct status updates even after the VG was setup initially.
Checks include:
- LV is present
- LV is of type Thin-Pool and was not wrongly converted
- lv is active
- has <95% metadata usage (as LVM will crash on most I/O if on entire thin-pool if there is a metadata volume overflow, as by consulting the man-page of lvm: `Metadata space exhaustion can lead to inconsistent thin pool metadata and inconsistent file systems, so the response requires offline checking and repair.`), allowing users to still circumvent with `lvextend --poolmetadatasize` in case of overprovisioning. This allow users to avoid having to reboot the node and repair the deactivated LV
=> OCPVE-616: fix: add check of correct lv state of thin-pool when vg is already created

controllers/persistent-volume-claim/controller.go, controllers/persistent-volume-claim/controller_test.go
If the capacity annotation (`capacity.topolvm.io/deviceClass`) does not exist on a node, that means the node is not used by LVMS. So, do not error, but just do not include it in the calculations during the capacity check.  
Change the implementation to use the corresponding annotation for the device class instead of using the default annotation.
=> OCPBUGS-17805: Do not error during capacity check if annotation does not exist on the node

pkg/vgmanager/devices.go, pkg/vgmanager/devices_test.go
It was discovered as part of the 4.14 verification process that the available devices check was creating an error due to not properly skipping devices that were already part of the volume group. This error would lead to a degraded state of the lvmcluster when the first reconciliation loop was initiated.
=> OCPBUGS-17848: fix: don't fail if devices already in vg

pkg/vgmanager/vgmanager_controller.go, pkg/vgmanager/vgmanager_controller_test.go
This adds more failure conditions where the LV could be corrupt and the LVMCluster will now go into degraded state.
Specifically three conditions are created:
1. If the `lvs` report of LVM is empty
2. If the `lvs` report of LVM is not empty but has no part for any LV
3. If the `lvs` report of LVM is not empty but only contains entries for LVs that are not the thin-pool we created.
For all three cases, previously the LVMCluster would remain in "Ready", now it will be "Degraded" instead
=> OCPVE-616: fix: add conditions to error on missing lv in case VG is present but thin-pool is not

controllers/persistent-volume-claim/controller.go, controllers/persistent-volume-claim/controller_test.go, controllers/persistent-volume/controller.go, go.mod, main.go
fix: do not error during capacity check if annotation does not exist on the node
fix: ensure panic safety in PVC controller for non-set storageClassName
=> [release-4.14] OCPBUGS-17857: Do not error during capacity check if annotation does not exist on the node

Dockerfile, Makefile
Allows building multi-arch images with ARCH / OS Flag from makefile. Also adjusts dockerfile to have the correct flags passed to the builder and running platform image.
=> OCPVE-361: chore: allow multi-arch with ARCH / OS Flag

Makefile
removes the old `e2e-test` target and adjusts the e2e target to use all relevant flags again.
also changes the defaults to not install / uninstall the operator
=> OCPVE-588: chore: adjust e2e makefile / remove e2e-test

controllers/internal/multierror.go, controllers/lvm_volumegroup.go, controllers/lvmcluster_controller.go, controllers/scc.go, controllers/topolvm_controller.go, controllers/topolvm_csi_driver.go, controllers/topolvm_node.go, controllers/topolvm_snapshotclass.go, controllers/topolvm_storageclass.go, controllers/utils.go, controllers/vgmanager.go
This PR introduces concurrent processing for the ensureCreated operations for each resourceManager in the LVMClusterReconciler controller, which significantly improves the overall reconciliation time for the `LVMCluster` custom resource.
The newly added `multierror.go` groups multiple errors into a single error, thereby helping to manage multiple errors generated from concurrent ensureCreated calls. This helps the concurrent apply since errors are not cancelled when one call fails, and multiple failures can occur at once.
Moreover, readiness checks have been added after the creation of Deployment and DaemonSet resources in the `topolvm_controller.go`, `topolvm_node.go`, and `vgmanager.go` files respectively.
These checks ensure that the deployment or `DaemonSet` has been completely …
=> OCPVE-627: fix: concurrent apply / status checks -> LVMCluster

README.md
Creates a guidance documentation on Snapshotting and Cloning in Multi-Node Topologies. It specifically recommends to use Stateful Sets alongside preprovisioned and bound source PVCs to avoid running into scheduler limitations that may (or may not) occur in TopoLVM CSI scheduling (I opened a discussion in https://github.com/topolvm/topolvm/discussions/737 to clarify the exact conditions, also I am trying to independently verify this issue).
=> OCPVE-620: docs: add guidance on Multi-Node Topology Snapshotting

controllers/lvm_volumegroup.go, controllers/lvmcluster_controller.go, controllers/lvmcluster_controller_watches.go, controllers/scc.go, controllers/suite_test.go, controllers/topolvm_controller.go, controllers/topolvm_csi_driver.go, controllers/topolvm_node.go, controllers/topolvm_snapshotclass.go, controllers/topolvm_storageclass.go, controllers/vgmanager.go, controllers/vgmanager_test.go, pkg/vgmanager/devices.go, pkg/vgmanager/devices_test.go, pkg/vgmanager/status.go, pkg/vgmanager/vgmanager_controller.go, pkg/vgmanager/vgmanager_controller_test.go
Removes all instances found of double logging and switches to context logging so we dont have to keep a logger instance in all structs.
=> OCPVE-644: chore: remove redundant err logging and use ctx for passing loggers

api/v1alpha1/lvmcluster_webhook.go, controllers/topolvm_storageclass.go, test/e2e/lvmcluster.go
This allows no default deviceClass to be present. Since this is a change from previous validation it now includes a warning if no default is set: "no default deviceClass was specified, it will be mandatory to specify the storage class"
TODO:
=> OCPVE-667: fix: allow no default deviceClass to be set

bundle/manifests/lvms-operator.clusterserviceversion.yaml, cmd/vgmanager/main.go, config/rbac/vg_manager_role.yaml, controllers/lvmcluster_controller.go, controllers/suite_test.go, controllers/utils.go, main.go, pkg/vgmanager/status.go, pkg/vgmanager/vgmanager_controller.go
This introduces event recorders to the lvm cluster controller as well as vg manager and issues events on the most important events and failures related to these resources.
=> OCPVE-663: feat: introduce k8s events to lvmcluster and vgmanager

controllers/lvmcluster_controller.go, controllers/lvmcluster_controller_watches.go, controllers/scc.go, controllers/suite_test.go, controllers/topolvm_csi_driver.go, controllers/topolvm_snapshotclass.go, controllers/topolvm_storageclass.go, controllers/vgmanager.go, main.go, pkg/labels/managed.go, pkg/vgmanager/status.go, pkg/vgmanager/vgmanager_controller.go
This updates all cluster-scoped subresources to have 6 new labels useful for filtering and assignments (in place of the usual ownerreference) - csidriver, volumesnapshotclass,scc,storageclass will now receive these labels. These labels are also used to filter the watch to stop watching for unnecessary objects in the cluster.
On top of this, now LVMVolumeGroupNodeStatus receives OwnerReferences from LVMVolumeGroup. We can later decide to upgrade them to blockOwnerDeletion as well, but currently its a normal OwnerReference (no controller reference to avoid conflicts between multiple volume groups on one NodeStatus). If the volumegroup disappears from the node, so does the owner reference.
Snapshotting was moved to a similar check as SecurityContextConstraints to also allow a watch on the …
=> OCPBUGS-18354: owns watches config updates

controllers/vgmanager.go
This removes the 6 labels that were introduces as part of #405 for the vgmanager DaemonSet since it contains a normal ownerreference and doesnt need these labels. They were commited by accident. No legacy removal necessary since we never released a version for this change
=> OCPBUGS-18354: chore: remove unnecessary labels from vg manager DaemonSet

pkg/vgmanager/vgmanager_controller.go
Part of the findings of testing vgmanager. This allows us to delete LVMVolumeGroups even if the lvmd.conf file was previously deleted. This can also happen in case the LVMVolumeGroup creation failed and we want to remove the LVMVolumeGroup. In this case, the lvmd.conf file never existed in the first place and it would previously stop the LVMVolumeGroup from being deleted. Now, whenever the lvmd.conf file is not found, we just skip the deletion of the lvmd.conf entry.
=> OCPVE-677: fix: allow deletion of lvmvolumegroup if lvmd conf was already deleted

pkg/filter/filter.go, pkg/filter/filter_test.go, pkg/lvm/lvm.go, pkg/lvm/lvm_test.go, pkg/vgmanager/devices.go, pkg/vgmanager/devices_test.go, pkg/vgmanager/status.go, pkg/vgmanager/vgmanager_controller.go
Part of the findings of vgmanager testing. This separates vgmanager into 3 packages:
1. lvm, now contains ALL calls to LVM in the codebase
2. filter, now contains our filter methods and gets included from vgmanager
3. vgmanager, now only calls to lvm and filter in the correct places
Also the previously raw command executor calls for thinpool creation/extension were moved into separate methods in lvm package so that the perogative to contain all lvm calls still remains.
=> OCPVE-677: chore: separate filter and lvm package from vgmanager

controllers/lvm_volumegroup.go, controllers/scc.go, controllers/topolvm_snapshotclass.go, controllers/topolvm_storageclass.go
Part of vgmanager refactor. For resourceManagers managing multiple resources, previously the delete aborted if one of the managed resources was not found. Now it properly continues until all resources are no longer found. This applies to LVMVolumeGroup, SCCs, VolumeSnapshotClass and StorageClass
=> OCPVE-677: fix: allow deleting all storageclasses / vgs in case one is already gone

controllers/lvmcluster_controller.go
This removes an accidentally leftover part in the default resources that should have been replaced with a conditional removal in https://github.com/openshift/lvm-operator/pull/422/files#diff-2149d6865f2c29cbc9e17358f35e710ddf91b49d334e66a3211b432dea0ba747L398-L400
instead.
=> OCPBUGS-18354: fix: remove volumesnapshotclass from default resource deletion list

api/v1alpha1/lvmcluster_test.go, api/v1alpha1/lvmcluster_webhook.go, api/v1alpha1/webhook_suite_test.go, main.go, pkg/cluster/namespace.go
Introduces 2 new Limitations and tests for them in the Creation of LVMClusters:
1. LVMCluster Duplicates in one namespace are not allowed
2. LVMCluster can only be created in the Namespace of the Operator introspected by `POD_NAMESPACE`
This leads to us only being allowed exactly one LVMCluster in the Namespace of the operator
=> OCPBUGS-18708: fix: disallow creation of LVMCluster outside of operator namespace and restrict cache

Dockerfile, Makefile, bundle/manifests/lvms-operator.clusterserviceversion.yaml, cmd/main.go, cmd/operator/operator.go, cmd/vgmanager/vgmanager.go, config/manager/manager.yaml, controllers/vgmanager_daemonset.go, go.mod
This uses cobra to unify the vgmanager and lvm operator binaries under a single binary so we only have to run go build once (speeds up compile time x2), and also optimizes the dockerfile to reuse the vendor directory instead of calling `go mod download` every time, further speeding up builds by about 10-20s (depending on how long downloading takes, much faster for slower connections). Also moves all binaries under `cmd` and removes top level `main.go`
=> OCPVE-707: chore: unify build binaries and optimize dockerfile

CONTRIBUTING.md, Makefile, cmd/operator/operator.go, config/debug/kustomization.yaml, config/debug/manager_debug_patch.yaml, hack/debug.Dockerfile, internal/controllers/lvmcluster/lvmcluster_controller.go, internal/controllers/lvmcluster/resource/manager.go, internal/controllers/lvmcluster/resource/vgmanager.go, internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
Introduces a new flag to pass the command to the created vg manager daemonset and introduces two new make targets: `docker-build-debug` and `deploy-debug` which use a delve enabled dockerfile that allows remote attachment in the cluster for debugging purposes.
One can attach to the application by running a port-forward to either `lvm-operator` or `vgmanager` on port `2345`. Then one can remotely attach the debugger as per https://www.jetbrains.com/help/go/attach-to-running-go-processes-with-debugger.html#step-3-create-the-remote-run-debug-configuration-on-the-client-computer or https://github.com/golang/vscode-go/blob/master/docs/debugging.md#connect-to-headless-delve-with-target-specified-at-server-start-up
=> OCPVE-709: feat: allow dlv debugging for lvm operator and vgmanager

Dockerfile
removes a wrongly introduced mount for the docker build cache that was committed by accident
=> OCPVE-346: fix: remove build cache mount

cmd/main.go, cmd/operator/operator.go, go.mod, internal/controllers/lvmcluster/logpassthrough/options.go, internal/controllers/lvmcluster/logpassthrough/options_test.go, internal/controllers/lvmcluster/lvmcluster_controller.go, internal/controllers/lvmcluster/resource/manager.go, internal/controllers/lvmcluster/resource/topolvm_controller.go, internal/controllers/lvmcluster/resource/topolvm_node.go, internal/controllers/lvmcluster/resource/vgmanager.go, internal/controllers/lvmcluster/resource/vgmanager_daemonset.go, internal/controllers/lvmcluster/suite_test.go, internal/controllers/lvmcluster/vgmanager_test.go
Allows passing through log verbosity settings for `vgmanager`, `topolvm-controller`, `topolvm-node` and `lvmd` and all csi-sidecar containers (resizer, snapshotter, external-provisioner, registrar). The flags are passed generically with a prefix that is attached to them and they will only be passed if they differ from the default value. LVMD supports less than usual flags as it uses a legacy logging library from cybozu.
This is the new help with all flags available in the operator:
```
./bin/lvms operator --help
Operator reconciling LVMCluster LVMVolumeGroup and LVMVolumeGroupNodeStatus
Usage:
lvms operator [flags]
Flags:
--csi-sidecar-v string                      csi-sidecar: number for the log level verbosity
--csi-sidecar-vmodule string                csi-sidecar: comma-separated list …
```
=> OCPVE-343: feat: allow passthrough for log flags

Makefile, bundle.Dockerfile, bundle/manifests/lvms-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml
Also adds a sed modification to remove `createdAt` from the bundle to avoid change detection triggers. Since its a generic annotation and the bundle validate succeeds we can assume this is safe
=> OCPVE-710: chore: bump OPERATOR_SDK_VERSION to 1.32.0

cmd/vgmanager/vgmanager.go, cmd/vgmanager/vgmanager_test.go, internal/controllers/vgmanager/lvm/lvm.go, internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
This PR adds an `lvms` tag to the volume groups used by LVMS. Also, this implements a temporary logic to add the tag to the existing volume groups, which is useful especially for upgrades.
=> OCPVE-603: Add lvms tag to volume groups

internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/controller_test.go, internal/controllers/vgmanager/lvm/lvm.go, internal/controllers/vgmanager/lvm/mocks/mock_lvm.go
This PR adds a logic to activate the inactive logical volumes. This is important for the recovery scenario where the leftover logical volumes from a previous installation can be inactive and need to be activated to be used in LVMS.
=> OCPVE-726: Activate inactive logical volumes

internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/devices.go
This PR allows LVMS to pick up and use an existing volume group if it has the same name as the reconciled LVMVolumeGroup name.
=> OCPVE-605: Allow recovering from existing volume groups

Makefile, catalog.Dockerfile, catalog/channel.yaml, catalog/lvms-operator/operator.yaml, catalog/package.yaml, hack/verify-catalog.sh
Migrates the index based bundling to the File Based Catalog format https://olm.operatorframework.io/docs/reference/file-based-catalogs/#opm-init
Creates a `catalog` directory in the repo that contains the FBC data. Also introduces a new `verify-catalog` script together with adjustments to the makefile to ensure that a catalog can always be built from the bundle image. 
Existing commands `catalog-build` and `catalog-push` are not touched, they simply now use a newer version of OPM and different commands under the hood. behavior is exactly the same as before in terms of use, and the `deploy-with-olm` command works the same as before
=> OCPVE-738: feat: migrate to FBC for catalog in makefile

cmd/vgmanager/vgmanager.go, internal/tagging/tagging.go, internal/tagging/tagging_test.go
Moves the temporary tagging logic for 4.15 out into an internal package so that coverage doesn't attempt to cover the cmd package (which is CLI interfacing that we don't want to test)
=> OCPVE-747: chore: move tagging to avoid coverage on cmd

docs/design/architecture.md, docs/design/lvm-operator-manager.md, internal/controllers/constants/constants.go, internal/controllers/lvmcluster/logpassthrough/options.go, internal/controllers/lvmcluster/logpassthrough/options_test.go, internal/controllers/lvmcluster/resource/topolvm_node.go, internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/controller_test.go
uses embed-lvmd as a feature in order to reduce memory footprint and container count
=> OCPVE-766: feat: use embed-lvmd instead of container

cmd/operator/operator.go
Since we dont have any shutdown logic on LVMS post manager exit, we can safely drop leader election and quicken the restart process.
=> OCPBUGS-11486: fix: immediately drop leader election in case of shutdown to quicken restart

cmd/operator/operator.go
Turns out that the openshift leader election Lock is not 1:1 compatible to the controller runtime lock interface even though it can be passed. This is because the Lock looses communication to the API server through a context cancel and thus is forced by controller runtime to restart. The new lock configuration this PR provides only uses the correct Lease/Retry/Skew values, but uses the native controller runtime implementation for actually setting up the Lease object and tracking it. That way the restart is prohibited.
=> OCPBUGS-11486: fix: use native leader lock implementation

README.md
This adds an additional limitation information to the docs which brings notice to the fact that the LVMCluster Validation does not work outside of the deployed openshift-storage namespace when deploying it via ClusterServiceVersion
=> OCPBUGS-18708: docs: add validation limitation

bundle/manifests/lvms-operator.clusterserviceversion.yaml, cmd/operator/operator.go, config/rbac/role.yaml, internal/controllers/lvmcluster/controller_integration_test.go, internal/controllers/lvmcluster/suite_test.go, internal/controllers/node/removal/controller.go, internal/controllers/node/removal/controller_test.go
This refactors the node removal controller to not require a finalizer anymore on the node.
It does this by watching LVMVolumeGroupNodeStatus instead of Node as its base reconciled object. This allows us to drop the Field Indexer for Nodes and also 2 permissions on the Node reconciler. Additionally it should make the deletion much more stable and we now run the reconciler not only on SNO, but on all topologies because even SNO can technically add worker nodes.
Cases:
1. Node and NodeStatus are present - nothing happens
2. Node is present but NodeStatus isn't - removal reconciler ignores the node because its not finding a status to check
3. NodeStatus is present but Node isn't - removal controller fetches the node status on startup and on cache refresh, sees that the node is gone, and …
=> OCPBUGS-13558: fix: refactor node removal controller

bundle/manifests/lvms-operator.clusterserviceversion.yaml, cmd/vgmanager/vgmanager.go, config/rbac/vg_manager_role.yaml, internal/controllers/constants/constants.go, internal/controllers/lvmcluster/resource/topolvm_node.go, internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/controller_test.go, internal/controllers/vgmanager/lvmd/lvmd.go, internal/controllers/vgmanager/lvmd/mocks/mock_configurator.go
This PR changes the way how VG Manager supplies lvmd config to TopoLVM Node. The config file was saved as a file on the host before. Now, VG Manager creates a ConfigMap that is mounted to TopoLVM Node. This way, TopoLVM does not need the `file-checker` init-container anymore, hence it is deleted.
=> OCPVE-760: Save lvmd config to a configmap instead of a file

internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/controller_test.go
Sets "Failed" status correctly if the device Resolution resulted in an error. Previously it was set to progressing. Also a failure event of type "DevicePathCheckFailed" is issued and made visible in LVMCluster
=> OCPBUGS-23995: fix: set failed status on device check failure

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/manager/manager.yaml, internal/controllers/constants/constants.go, internal/controllers/lvmcluster/resource/topolvm_controller.go, internal/controllers/lvmcluster/resource/topolvm_node.go, internal/controllers/lvmcluster/resource/vgmanager.go, internal/controllers/lvmcluster/resource/vgmanager_daemonset.go
This PR adds priority class names to LVMS resources as per the OpenShift [conventions](https://github.com/openshift/enhancements/blob/6264168ccf099b74cc6258569e3c5e9be481ecd1/CONVENTIONS.md?plain=1#L222-L224).
=> OCPBUGS-23375: Add priority class name to lvms resources

bundle/manifests/lvms-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, config/prometheus/monitor.yaml
Removes the unnecessary scrape of topolvm-node since we no longer need to expose these separately from vgmanager
=> chore: remove topolvm-node from scrape

must-gather/collection-scripts/gather
The collection scripts can be executed in parallel to save time when running the MG.
Process:
1.Running gather scripts in parallel
2.Waiting for the subprocesses to finish execution.
=> NO-JIRA: Must-Gather, Running gather scripts in background

internal/controllers/lvmcluster/resource/topolvm_controller.go
Removes the unnecessary annotation patch that also overrode the deployment.kubernetes.io/revision annotation generated by the k8s controller causing additional spec generations
=> OCPBUGS-27330: fix: avoid topolvm-controller annotation generation increment

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/rbac/role.yaml, config/rbac/topolvm_controller_role.yaml, internal/controllers/lvmcluster/resource/scc.go, internal/controllers/lvmcluster/resource/topolvm_csi_driver.go, internal/controllers/lvmcluster/resource/topolvm_snapshotclass.go, internal/controllers/lvmcluster/resource/topolvm_storageclass.go
(cherry picked and adjusted from commit ac3ea44d0d6175254f3cc0ba99a4997198c2a281)
=> [release-4.15] OCPBUGS-27358: fix: add missing permissions to cluster scoped resources

api/v1alpha1/lvmcluster_test.go
Addresses the failure in the recent main run that was coming up during test execution
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-lvm-operator-main-post-unit-test/1749362544251768832#1:build-log.txt%3A133
=> NO-JIRA: fix: do not set resource version in lvmcluster test

catalog/lvms-operator/operator.yaml, internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/controller_test.go, internal/controllers/vgmanager/lvm/lvm.go, internal/controllers/vgmanager/lvm/lvm_test.go, internal/controllers/vgmanager/lvm/mocks/mock_lvm.go, internal/controllers/vgmanager/status.go, internal/tagging/tagging.go, internal/tagging/tagging_test.go
This PR solves 2 main issues:
1. The tagging migration used lvs that were already prefiltered by the tag
2. The tagging migration was using inefficient querying and always ran for all lvs, that now changed.
The test cases didnt reach all the paths so we didnt catch that.
=> [release-4.15] OCPBUGS-28966: fix: more sophisticated tagging migration

internal/controllers/lvmcluster/resource/topolvm_node.go
This PR fixes the 4.14 to 4.15 upgrade of TopoLVM Node. It currently fails as we introduced a new "metrics-cert" volume for TopoLVM Node in 4.15 and LVMS didn't reconcile the volumes.
=> OCPBUGS-29065: Reconcile topolvm node volumes

.pre-commit-config.yaml, internal/controllers/vgmanager/devices.go, internal/controllers/vgmanager/filter/filter.go, internal/controllers/vgmanager/filter/filter_test.go
This allows us to properly exclude and filter symlinked devices that would previously be compared via kname without being resolved. Now we compare them symlinked which results in proper filter results
Added precommit timeout and incremented golang ci lint version
=> OCPBUGS-29188: fix: resolve PV name via Symlink before comparing to KName

internal/controllers/vgmanager/devices.go, internal/controllers/vgmanager/filter/filter.go, internal/controllers/vgmanager/filter/filter_test.go
(cherry picked from commit f20496562d2af700b141f1aca86e9efcc47959dd)
=> [release-4.15] OCPBUGS-29351: fix: resolve PV name before comparing to KName

cmd/operator/operator.go
This removes managed fields for all objects since we do not make use of SSA and thus do not need to save the managed fields data for the objects and they will anyhow get ignored on client side apply.
=> OCPEDGE-781: chore: remove managed fields from all objs

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/constants.go, controllers/topolvm_controller.go, controllers/topolvm_node.go, controllers/vgmanager_daemonset.go
partial cherry-pick of 77dbf35ff3b666524e111b1ef7d854bf5f997d27
=> OCPBUGS-29699: fix: remove resource limits

cmd/operator/operator.go, go.mod, go.sum, internal/controllers/constants/constants.go, vendor/github.com/topolvm/topolvm/Makefile, vendor/github.com/topolvm/topolvm/internal/controller/node_controller.go, vendor/github.com/topolvm/topolvm/internal/driver/allocation_settings.go, vendor/github.com/topolvm/topolvm/internal/driver/controller.go, vendor/github.com/topolvm/topolvm/internal/driver/node.go, vendor/github.com/topolvm/topolvm/internal/lvmd/device_class_manager.go, vendor/github.com/topolvm/topolvm/internal/lvmd/lvservice.go, vendor/github.com/topolvm/topolvm/internal/lvmd/vgservice.go, vendor/github.com/topolvm/topolvm/pkg/driver/controller.go, vendor/github.com/topolvm/topolvm/versions.mk, vendor/modules.txt
This introduces minimum allocation sizing on the topolvm controller server equivalent to our upstream. The difference here is that we set our own limits so that we can later transition to a more dynamic configuration if required. For now the minimum limits should suffice.
=> OCPBUGS-30266: fix: introduce minimum allocation sizes

internal/controllers/lvmcluster/controller.go
This PR updates the readiness calculation logic to accommodate the case where readyVGCount is greater than expectedVGCount, e.g. during an upgrade.
=> OCPBUGS-30830: Accommodate the case in readiness calculation where readyVGCount is greater than expectedVGCount

must-gather/README.md, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_clusterscoped_resources, must-gather/collection-scripts/gather_common, must-gather/collection-scripts/gather_namespaced_resources
`oc adm must-gather` has new flags `--since` and `--since-time`, which set `MUST_GATHER_SINCE` and `MUST_GATHER_SINCE_TIME` environment vars to limit log collection based on a specified time. This PR adds support for these flags to LVMS must-gather.
=> OCPEDGE-1005: must-gather: add support for --since and --since-time flags

Dockerfile
Because of a recent bug (https://issues.redhat.com/browse/OCPBUGS-33244), we had to switch to a rhel base image which requires registry authentication. This is not ideal for development and is not accessible to external contributors. That's why we want to switch to a Fedora base image.
=> OCPEDGE-1085: Change the base image to fedora

internal/controllers/lvmcluster/controller.go, internal/controllers/lvmcluster/controller_integration_test.go, internal/controllers/lvmcluster/resource/lvm_volumegroupnodestatus.go
cherry-picks 0045d704522c706b34c778a714f41ed346d1c1b1
=> [release-4.15] OCPBUGS-33842: Remove LVMVolumeGroupNodeStatus CRs as well when LVMCluster CR is removed

internal/controllers/lvmcluster/controller.go, internal/controllers/lvmcluster/controller_integration_test.go, internal/controllers/lvmcluster/resource/lvm_volumegroupnodestatus.go, internal/controllers/lvmcluster/selector/selector.go, internal/controllers/lvmcluster/suite_test.go, internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/controller_test.go
When LVMVolumeGroupNodeStatus was originally created it was thought of to be fully managed by the LVMVolumeGroups reconciler in vg-manager. However this is problematic because there must always be 1 owner for full blockOwnerDeletion and Deletion Propagation to work in kubernetes (Controller Reference must be set from the Owner to the owning object). This is not possible with that approach. If we reimagine the LVMCluster to create LVMVolumeGroupNodeStatus instead (by precalculating the Nodes for which we should create a node status) we can achieve the following:
1. Create NodeStatus as soon as LVMCluster exists
2. Have a Finalizer that protects from dropping a NodeStatus prematurely (this can still lead to issues where vg-manager can no longer remove its own volume group from the status …
=> OCPBUGS-33304: fix: Rework LVMVolumeGroupNodeStatus management

Makefile, api/v1alpha1/lvmcluster_test.go, cmd/vgmanager/vgmanager.go, internal/controllers/lvmcluster/resource/topolvm_csi_driver.go, internal/controllers/lvmcluster/resource/vgmanager.go, internal/controllers/lvmcluster/resource/vgmanager_daemonset.go, internal/csi/grpc_runner.go, internal/csi/registrar.go, test/e2e/config_test.go, test/e2e/helper_test.go, test/e2e/lvm_cluster_test.go, test/e2e/lvm_pvc_test.go, test/e2e/lvm_suite_test.go, test/e2e/validation_test.go
This stops vgmanager from going healthy too early as we need to signal healthiness only when the driver has been started. Fixes the racy registration server that now properly starts and shuts down and is part of the healthiness check we use in vgmanager. That will ensure that no vgmanager gets ready that isnt registered in the kubelet. Ensures that vgmanager pods are gone before LVMCluster is freed.
Adds an artifact into the e2e step on failure that can be used to see the immediate LVMS cluster state when a failure occurs in case of a cleanup in the post failure steps.
Validates in tests that all CSINodes have proper registrations for vgmanager so we dont have weird flakes in the future.
=> OCPEDGE-1165: fix: Ensure no racy CSI plugin registration, better startup behavior for vgmanager, failing test summary artifact

internal/controllers/vgmanager/lvmd/lvmd.go
readjusts the mount directory to /var/lib to not induce conflicts with ostree state management. paths are still synchronized from /etc/topolvm via a watch from /etc to /var/lib in microshift
See https://github.com/openshift/microshift/pull/3535#discussion_r1653042872 for the reasoning background and https://github.com/openshift/microshift/pull/3535/commits/a66137a80fc6952ebc959f7f661df4dc734886cf for adjustment on the implementation on microshift
=> OCPEDGE-1126: feat: make lvms microshift aware during vgmanager mounting

controllers/topolvm_node.go
This adds a health probe that can be consumed as per https://github.com/openshift/topolvm/blob/release-4.14/pkg/lvmd/cmd/health.go
=> [release-4.14] OCPBUGS-35917: fix: add missing health probe on lvmd container

bundle/manifests/lvms-operator.clusterserviceversion.yaml, config/manifests/bases/clusterserviceversion.yaml.in
Cherry picking https://github.com/openshift/lvm-operator/pull/621 to resolve CVP errors.
=> [release-4.12] OCPBUGS-33087: chore: add OpenShift Kubernetes Engine to valid subscriptions

cmd/vgmanager/vgmanager.go, internal/controllers/lvmcluster/controller.go, internal/controllers/lvmcluster/resource/csi_node.go, internal/controllers/lvmcluster/suite_test.go, internal/csi/grpc_runner.go, internal/csi/health.go
This avoids the pod shutdown in case of healthiness errors, e.g. when the device class setup takes extremely long. This has the side effect of vgmanager possibly hanging up if there is a hangup in one of its servers, but it will show a not Ready State if that happens. Also now the node server only reports healthiness once this has been successfully completed.
This concretely fixes a situation in which the lvmd setup takes extremely long due to thinpool provisioning (e.g. 5 mins for zeroing a huge array of disks) and the kubelet would kill the pod due to the failing healthiness.
=> OCPBUGS-34227: fix: move checks into readiness and introduce grpc health

pkg/vgmanager/vgmanager_controller.go
The lvmd socket is currently not set if the file is empty or the socket name gets nilled out because the socket does not get reconciled on update, only on create. This PR fixes that.
=> [release-4.14] OCPBUGS-36368: fixup lvmd socket

.tekton/lvm-operator-bundle-pull-request.yaml, .tekton/lvm-operator-bundle-push.yaml, .tekton/lvm-operator-pull-request.yaml, .tekton/lvm-operator-push.yaml
Removed as per https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md.
=> NO-JIRA: chore: remove deprecated BASE_IMAGES_DIGESTS from Konflux jobs

internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/controller_test.go, internal/controllers/vgmanager/devices.go, internal/controllers/vgmanager/devices_test.go, internal/controllers/vgmanager/filter/filter.go, internal/controllers/vgmanager/filter/filter_test.go, internal/controllers/vgmanager/lsblk/lsblk.go, internal/controllers/vgmanager/lvm/lvm.go, internal/controllers/vgmanager/lvm/lvm_test.go, internal/controllers/vgmanager/wipe_devices.go, internal/controllers/vgmanager/wipe_devices_test.go
This changes our device selection methodology to try to unify all selection criteria into the filters.
Previously, we had a complex flow with getNewDevicesToBeAdded and filters together.
This now changes this so that all filter criteria are purely handled through filterDevices.
It achieves this by:
1. Creating a new filter function to verify that a block device must be part of the deviceSelector if the deviceSelector is present, otherwise this is a no-op filter
2. Introducing `VerifyMandatoryDevicePaths(devs FilteredBlockDevices, paths[]string) error` as a shortcut to determine if a given path is already setup. This can be used together with `.Spec.storage.deviceClasses[].deviceSelector.Paths` to ensure presence of mandatory paths. For optional paths this check is simply skipped
=> OCPEDGE-1169: fix: device selection only by filter

internal/controllers/lvmcluster/resource/csi_node.go, internal/controllers/vgmanager/dmsetup/dmsetup.go, internal/controllers/vgmanager/dmsetup/dmsetup_test.go, internal/controllers/vgmanager/exec/exec.go, internal/controllers/vgmanager/exec/test/mock_exec.go, internal/controllers/vgmanager/wipe_devices.go, internal/controllers/vgmanager/wipefs/wipefs.go, internal/controllers/vgmanager/wipefs/wipefs_test.go
This fix is a set of corrections applied to our wiping behavior in order to prohibit a race between different command invocations:
for given
```
for given 
lsblk -o Kname,name
(vdb was created with one partition (type 8E), after which a vg and lv thin pool have been created on it)
vdb   vdb
vdb1  `-vdb1
dm-0    |-some--other--vg-some--lv_tmeta
dm-2    | `-some--other--vg-some--lv
dm-1    `-some--other--vg-some--lv_tdata
dm-2      `-some--other--vg-some--lv
```
the commands will now be
```
dmsetup remove --force /dev/dm-2
dmsetup remove --force /dev/dm-0
dmsetup remove --force /dev/dm-2 //no-op
dmsetup remove --force /dev/dm-1
wipefs --all --force /dev/vdb // will do ioctl reload and cause partition table refresh
```
Previously, we encountered an issue because we used the …
=> OCPBUGS-37711: fix: ensure wipefs / dmsetup remove use CombinedOutput to wait for both STDERR and STDOUT before continuing

internal/controllers/lvmcluster/controller.go, internal/controllers/lvmcluster/status.go, internal/controllers/lvmcluster/status_test.go
When the resource syncrhonization fails (e.g. because of an irrepairable error due to cluster state or due to the CSI node not being synchronized) we should move the status to progressing. That is because all of the resource sync problems are either resolvable automatically (after a certain time), or can be remediated by the user through changes in the cluster.
There is an edge that if we configure the pods wrong in the reconcile, then we have a permanent failure with state Progressing. However this is still technically correct since the Reconciler will keep trying to apply the resources (as opposed to perceived Failed which users would expect to not conclude with a retry)
=> OCPBUGS-37844: fix: resource sync fail -> progressing

CONTRIBUTING.md, api/v1alpha1/lvmcluster_test.go, api/v1alpha1/lvmcluster_types.go, api/v1alpha1/lvmcluster_webhook.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/main.go, cmd/vgmanager/vgmanager.go, docs/design/lvm-operator-manager.md, hack/debug.Dockerfile, internal/controllers/symlink-resolver/resolver.go, internal/controllers/symlink-resolver/resolver_test.go, internal/controllers/vgmanager/controller.go, internal/controllers/vgmanager/controller_test.go, internal/controllers/vgmanager/devices.go, internal/controllers/vgmanager/devices_test.go, internal/controllers/vgmanager/filter/filter.go, internal/controllers/vgmanager/filter/filter_test.go, internal/controllers/vgmanager/kname_test.go, internal/controllers/vgmanager/wipe_devices.go, internal/controllers/vgmanager/wipe_devices_test.go, test/performance/collector.go, test/performance/parse.go
Introduce a new type called DevicePath to contain user provided device path. This is done in order to create a standard way of working with resolved if symlink or raw(unresolved) device path and avoid errors when it's not resolved while it's expected to be.
=> OCPEDGE-1168: change DevicePath field to its own type 

docs/troubleshooting.md
This PR adds a graceful recovery documentation for the 2 main failure cases in LVMS
1. Disk Failure of a multi-disk volume group
2. Node Failure of a multi-node deviceClass
=> OCPBUGS-35072: docs: graceful recovery documentation

Makefile, config/default/kustomization.yaml, config/manager/kustomization.yaml, config/manifests/kustomization.yaml, config/prometheus/kustomization.yaml, config/webhook/kustomization.yaml
This PR runs prometheus kustomization applies separately from the base kustomization with the makefile ignore `-` instruction, causing make to ignore any errors from applying to a cluster that does not have the monitoring CRDs installed (e.g. non-openshift).
Also makes the debug deploy easier to maintain by removing duplicated parts in the makefile
=> OCPBUGS-13236: fix: allow deploy on cluster without prometheus

cmd/vgmanager/vgmanager.go, internal/controllers/lvmcluster/resource/vgmanager_daemonset.go, internal/controllers/vgmanager/util/startlock.go
Alternative to https://github.com/openshift/lvm-operator/pull/707 which should allow for termination grace period, but also prohibit parallel container starts
=> OCPEDGE-1249: fix: introduce vgmanager file lock on start

internal/controllers/vgmanager/devices.go, internal/controllers/vgmanager/devices_test.go
Ensure that for device mapper devices that are exposed under multiple children, we report the device at most once. Otherwise we can have multiple available devices that will error out in the vgcreate process. An example is an mdadm raid array, so I added a test case to confirm this.
=> OCPBUGS-41632: fix: ensure uniq available devices

cmd/operator/operator.go, cmd/vgmanager/vgmanager.go
Manual backport of https://github.com/openshift/lvm-operator/pull/711
=> [release-4.15]NO-JIRA: feat(controller): disable http2

cmd/operator/operator.go, internal/migration/wipe-refactor/annotate.go, internal/migration/wipe-refactor/annotate_test.go
This PR introduces migration logic for updates to the wipe feature in version 4.17. Previously, the LVM Operator used the `LVMVolumeGroupNodeStatus` resource to verify if a device was wiped—if the device appeared in a VG under `LVMVGStatus`, it was considered wiped. In 4.17, we refactored this approach to rely on the `wiped.devices.lvms.openshift.io` annotation within an `LVMVolumeGroup`, indicating whether all devices in the VG have been wiped. However, during upgrades from 4.16 to 4.17 or 4.18, the LVM Operator would re-wipe devices due to the missing annotation. This migration logic resolves that by checking existing `LVMVolumeGroupNodeStatus` resources in the operator namespace and applying the necessary annotations to `LVMVolumeGroups`.
=> OCPBUGS-44377: Add migration logic for wipe refactor

must-gather/collection-scripts/gather_namespaced_resources
Previously, due to a typo in the lvmvolumegroupnodestatus resource name within the must-gather script, only the 'get' output was collected, while the 'describe' output was missing. This fix corrects the resource name, ensuring that both 'get' and 'describe' outputs are properly gathered.
=> NO-JIRA: Fix typo in lvmvolumegroupnodestatus during lvm must-gather collection

internal/controllers/lvmcluster/controller_watches.go, internal/controllers/node/removal/controller.go, internal/controllers/persistent-volume-claim/controller.go, internal/controllers/persistent-volume/controller.go, internal/controllers/vgmanager/controller.go
With new controller runtime kubernetes introduced controller name check. Because of that, graceful restarts started to fail. Because there are no other workaround - we simply disable this check
=> OCPEDGE-1593: feat(controller): skip controller name validation

.tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml, release/hack/update-konflux-task-refs.sh, release/konflux.make
- Update to the latest manifests for task images
- Added a script to automate manifest updates
- Added a make target for update konflux dependencies `make konflux-update`
- Currently this just calls the new target for updating task manifests, we can build this out to add other scripts down the line
=> NO-JIRA: chore: build pipeline updates, added a script for automation

internal/controllers/lvmcluster/controller.go, internal/controllers/lvmcluster/resource/csi_node.go, internal/controllers/lvmcluster/resource/lvm_volumegroupnodestatus.go, internal/controllers/lvmcluster/selector/selector.go, internal/controllers/lvmcluster/status.go
This PR 
- Adds logic to return a reconciliation error in case one of the nodes has a `node.kubernetes.io/not-ready` taint
- Makes lvm-operator reconcile once a minute to catch any changes not caught by the watches.
=> OCPBUGS-52351: Retry Nodes with not-ready taint

test/e2e/aws_disk_test.go, test/e2e/disk_setup_test.go
read aws credentials from disk instead of creating a secret with them via additional ci step
=> OCPEDGE-1921: feat(test): update e2e aws client creation

release/operator/konflux.Dockerfile
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> KONFLUX-6210: chore: fix and set name and cpe label for lvm-operator-4-19

release/bundle/bundle.konflux.Dockerfile
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> chore(KONFLUX-6210): fix and set name and cpe label for lvm-operator-bundle-4-19
